### ISSUE TITLE
Make Exclusion for Mobs from a Spawner

### ISSUE THREAD

**Issue by Cokenpizza** [portalsam1/MagicHealth#1]
An option to deny magichealth items from mobs that came from a mob spawner would be great.  Even with a low chance of loot, the sheer volume of mobs from a spawner make it very easy to accumulate hearts.

**Comment by portalsam1** [comment]
Added in 1.4.5
https://github.com/portalsam1/MagicHealth/releases/tag/1.4.5-Release
